# Data EDA and visualization

### Importing required libraries

In [68]:
import numpy as np
import pandas as pd
import math

In [69]:
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, QuantileTransformer
from sklearn.preprocessing import LabelEncoder

In [49]:
data = pd.read_csv('csv_data.csv')

In [50]:
data.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,NaN,No,...,NaN,NaN,NaN,No,No,Yes,No,"Yes, received tetanus shot but not sure what type",No,No
1,Alabama,Female,Excellent,0.0,0.0,NaN,No,6.0,NaN,No,...,1.60,68.04,26.57,No,No,No,No,"No, did not receive any tetanus shot in the pa...",No,No
2,Alabama,Female,Very good,2.0,3.0,Within past year (anytime less than 12 months ...,Yes,5.0,NaN,No,...,1.57,63.50,25.61,No,No,No,No,NaN,No,Yes
3,Alabama,Female,Excellent,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,7.0,NaN,No,...,1.65,63.50,23.30,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No
4,Alabama,Female,Fair,2.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,NaN,No,...,1.57,53.98,21.77,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,No

### NULL values in data

In [51]:
data.isnull().sum()

State                            0
Sex                              0
GeneralHealth                 1198
PhysicalHealthDays           10927
MentalHealthDays              9067
LastCheckupTime               8308
PhysicalActivities            1093
SleepHours                    5453
RemovedTeeth                 11360
HadHeartAttack                3065
HadAngina                     4405
HadStroke                     1557
HadAsthma                     1773
HadSkinCancer                 3143
HadCOPD                       2219
HadDepressiveDisorder         2812
HadKidneyDisease              1926
HadArthritis                  2633
HadDiabetes                   1087
DeafOrHardOfHearing          20647
BlindOrVisionDifficulty      21564
DifficultyConcentrating      24240
DifficultyWalking            24012
DifficultyDressingBathing    23915
DifficultyErrands            25656
SmokerStatus                 35462
ECigaretteUsage              35660
ChestScan                    56046
RaceEthnicityCategory        14057
AgeCategory                   9079
HeightInMeters               28652
WeightInKilograms            42078
BMI                          48806
AlcoholDrinkers              46574
HIVTesting                   66127
FluVaxLast12                 47121
PneumoVaxEver                77040
TetanusLast10Tdap            82516
HighRiskLastYear             50623
CovidPos                     50764
dtype: int64

We will remove NULL values present in the data

In [52]:
print(f"Old data shape: {data.shape}")
data = data.dropna()
print(f"No NULL data shape: {data.shape}")

Old data shape: (445132, 40)
No NULL data shape: (246022, 40)

### Duplicate records in data

In [53]:
data.duplicated().sum()

9

We will remove the duplicate records in data

In [54]:
print(f"Old data shape: {data.shape}")
data = data.drop_duplicates()
print(f"No duplicates data shape: {data.shape}")

Old data shape: (246022, 40)
No duplicates data shape: (246013, 40)

### Description of data

In [55]:
data.describe()

,PhysicalHealthDays,MentalHealthDays,SleepHours,HeightInMeters,WeightInKilograms,BMI
count,246013.000000,246013.000000,246013.000000,246013.000000,246013.000000,246013.000000
mean,4.119055,4.167292,7.021312,1.705150,83.615522,28.668258
std,8.405803,8.102796,1.440698,0.106654,21.323232,6.514005
min,0.000000,0.000000,1.000000,0.910000,28.120000,12.020000
25%,0.000000,0.000000,6.000000,1.630000,68.040000,24.270000
50%,0.000000,0.000000,7.000000,1.700000,81.650000,27.460000
75%,3.000000,4.000000,8.000000,1.780000,95.250000,31.890000
max,30.000000,30.000000,24.000000,2.410000,292.570000,97.650000

### Value Counts of the target feature 'HadHeartAttack'

In [56]:
data['HadHeartAttack'].value_counts()

HadHeartAttack
No     232578
Yes     13435
Name: count, dtype: int64

As we can see, the data is imbalanced and is skewed.<br>
We will fix this later in the project.

### Value Counts of the rest of the data

In [57]:
for feature, feature_type in zip(data.columns.to_list(), data.dtypes.to_list()):
    if feature_type == 'object' and feature != 'HadHeartAttack':
        print(data[feature].value_counts(), end='\n\n')

State
Washington              14998
Maryland                 9163
Minnesota                9161
Ohio                     8995
New York                 8923
Texas                    7408
Florida                  7315
Kansas                   6145
Wisconsin                6126
Maine                    6013
Iowa                     5672
Hawaii                   5596
Virginia                 5565
Indiana                  5502
South Carolina           5471
Massachusetts            5465
Arizona                  5461
Utah                     5373
Michigan                 5370
Colorado                 5159
Nebraska                 5107
California               5096
Connecticut              5053
Georgia                  4978
Vermont                  4844
South Dakota             4404
Montana                  4264
Missouri                 4195
New Jersey               3966
New Hampshire            3756
Puerto Rico              3589
Idaho                    3468
Alaska                   3205
Rhode Island             3111
Oregon                   3049
Louisiana                3010
West Virginia            2974
New Mexico               2968
Oklahoma                 2941
Arkansas                 2940
Pennsylvania             2729
Tennessee                2725
Illinois                 2607
North Carolina           2551
North Dakota             2498
Mississippi              2438
Kentucky                 2413
Wyoming                  2410
Delaware                 2155
Alabama                  1902
Nevada                   1769
District of Columbia     1725
Guam                     1549
Virgin Islands            743
Name: count, dtype: int64

Sex
Female    127806
Male      118207
Name: count, dtype: int64

GeneralHealth
Very good    86996
Good         77407
Excellent    41522
Fair         30658
Poor          9430
Name: count, dtype: int64

LastCheckupTime
Within past year (anytime less than 12 months ago)         198144
Within past 2 years (1 year but less than 2 years ago)      23227
Within past 5 years (2 years but less than 5 years ago)     13744
5 or more years ago                                         10898
Name: count, dtype: int64

PhysicalActivities
Yes    191310
No      54703
Name: count, dtype: int64

RemovedTeeth
None of them              131585
1 to 5                     74701
6 or more, but not all     25949
All                        13778
Name: count, dtype: int64

HadAngina
No     231060
Yes     14953
Name: count, dtype: int64

HadStroke
No     235902
Yes     10111
Name: count, dtype: int64

HadAsthma
No     209486
Yes     36527
Name: count, dtype: int64

HadSkinCancer
No     224994
Yes     21019
Name: count, dtype: int64

HadCOPD
No     227019
Yes     18994
Name: count, dtype: int64

HadDepressiveDisorder
No     195393
Yes     50620
Name: count, dtype: int64

HadKidneyDisease
No     234729
Yes     11284
Name: count, dtype: int64

HadArthritis
No     161132
Yes     84881
Name: count, dtype: int64

HadDiabetes
No                                         204827
Yes                                         33811
No, pre-diabetes or borderline diabetes      5392
Yes, but only during pregnancy (female)      1983
Name: count, dtype: int64

DeafOrHardOfHearing
No     224981
Yes     21032
Name: count, dtype: int64

BlindOrVisionDifficulty
No     233787
Yes     12226
Name: count, dtype: int64

DifficultyConcentrating
No     219793
Yes     26220
Name: count, dtype: int64

DifficultyWalking
No     209945
Yes     36068
Name: count, dtype: int64

DifficultyDressingBathing
No     237673
Yes      8340
Name: count, dtype: int64

DifficultyErrands
No     229629
Yes     16384
Name: count, dtype: int64

SmokerStatus
Never smoked                             147731
Former smoker                             68524
Current smoker - now smokes every day     21659
Current smoker - now smokes some days      8099
Name: count, dtype: int64

ECigaretteUsage
Never used e-cigarettes in my entire life    190119
Not at all (right now)                        43281
Use them some days                             6658
Use them every day                             5955
Name: count, dtype: int64

ChestScan
No     141818
Yes    104195
Name: count, dtype: int64

RaceEthnicityCategory
White only, Non-Hispanic         186327
Hispanic                          22570
Black only, Non-Hispanic          19330
Other race only, Non-Hispanic     12205
Multiracial, Non-Hispanic          5581
Name: count, dtype: int64

AgeCategory
Age 65 to 69       28555
Age 60 to 64       26719
Age 70 to 74       25737
Age 55 to 59       22224
Age 50 to 54       19912
Age 75 to 79       18133
Age 80 or older    17816
Age 40 to 44       16973
Age 45 to 49       16753
Age 35 to 39       15614
Age 30 to 34       13346
Age 18 to 24       13122
Age 25 to 29       11109
Name: count, dtype: int64

AlcoholDrinkers
Yes    135299
No     110714
Name: count, dtype: int64

HIVTesting
No     161513
Yes     84500
Name: count, dtype: int64

FluVaxLast12
Yes    131188
No     114825
Name: count, dtype: int64

PneumoVaxEver
No     146128
Yes     99885
Name: count, dtype: int64

TetanusLast10Tdap
No, did not receive any tetanus shot in the past 10 years    81743
Yes, received tetanus shot but not sure what type            74118
Yes, received Tdap                                           70282
Yes, received tetanus shot, but not Tdap                     19870
Name: count, dtype: int64

HighRiskLastYear
No     235437
Yes     10576
Name: count, dtype: int64

CovidPos
No                                                               167297
Yes                                                               70324
Tested positive using home test without a health professional      8392
Name: count, dtype: int64

### Correlation in the data

In [60]:
features = zip(data.columns.to_list(), data.dtypes.to_list())
for feature, feature_type in features:
    if feature_type == 'object':
        label_encoder = LabelEncoder()
        data[feature] = label_encoder.fit_transform(data[feature])

In [75]:
data.corr()['HadHeartAttack'].apply(lambda x: abs(x)).sort_values()

State                        0.002085
SleepHours                   0.003634
TetanusLast10Tdap            0.010006
HIVTesting                   0.014565
ECigaretteUsage              0.015482
CovidPos                     0.020968
HighRiskLastYear             0.021129
GeneralHealth                0.021599
HeightInMeters               0.023059
HadDepressiveDisorder        0.023701
HadAsthma                    0.023759
RaceEthnicityCategory        0.024206
MentalHealthDays             0.025888
BMI                          0.030409
WeightInKilograms            0.038432
FluVaxLast12                 0.045242
HadSkinCancer                0.049415
DifficultyConcentrating      0.051661
LastCheckupTime              0.065852
BlindOrVisionDifficulty      0.072962
Sex                          0.073317
RemovedTeeth                 0.073714
AlcoholDrinkers              0.074176
SmokerStatus                 0.077334
DifficultyDressingBathing    0.083089
PhysicalActivities           0.083186
DifficultyErrands            0.089492
DeafOrHardOfHearing          0.097660
HadKidneyDisease             0.109353
HadArthritis                 0.117772
PneumoVaxEver                0.119965
HadCOPD                      0.133220
PhysicalHealthDays           0.133422
HadDiabetes                  0.135104
DifficultyWalking            0.159884
ChestScan                    0.167766
AgeCategory                  0.172181
HadStroke                    0.177149
HadAngina                    0.445902
HadHeartAttack               1.000000
Name: HadHeartAttack, dtype: float64

Features with very correlations are strong features